version: "2"

run:
  timeout: 3m

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - ineffassign
    - bodyclose
    - sqlclosecheck
    - godox
    - misspell
  settings:
    govet:
      enable-all: true
    godox:
      keywords:
        - TODO
        - FIXME
        - BUG
        - HACK
  exclusions:
    rules:
      - linters:
          - godox
        path: ".*"

formatters:
  enable:
    - gofmt
    - goimports