version: "2"

run:
  timeout: 3m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - ineffassign
    - bodyclose
    - sqlclosecheck
    - godox
  settings:
    govet:
      enable-all: true
    godox:
      keywords:
        - TODO
        - FIXME
        - BUG
        - HACK
issues:
  exclude-rules:
    - linters:
        - godox

formatters:
  enable:
    - gofmt
    - goimports