FROM golang:1.27.0 AS builder

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /kafkatopics ./cmd/kafkatopics

FROM apache/kafka:3.9.0

COPY --from=builder /kafkatopics /kafkatopics
COPY scripts/kafka-init.sh /kafka-init.sh

ENTRYPOINT ["/kafka-init.sh"]
